enabled: true
dropdown:
  enabled: true
production-mode: false
slogan: 'AYUDA DE GRAV EN ESPAÑOL'
blog_page: /blog
footer:
  title: ABOUT
  description: 'Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod amet placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at phasellus sed ultricies.'
  copyright_text: 'DESIGN: <a href="https://html5up.net/" target="_blank">HTML5 UP</a>. IMAGES: <a href="http://wallpaperswide.com/" target="_blank">WALLPAPESWIDE</a>.'
  button_url: about
  button_text: 'Show more'
social:
  -
    name: Twitter
    url: 'https://www.twitter.com'
    icon: 'fa fa-twitter'
  -
    name: Facebook
    url: 'https://www.facebook.com'
    icon: 'fa fa-facebook'
  -
    name: Instagram
    url: 'https://www.instagram.com'
    icon: 'fa fa-instagram'
miniposts: true
miniposts_number: 3
latestposts: true
miniposts_category: miniposts
displaycustommenus:
  enabled: false
custommenu:
  -
    text: Grav
    icon: arrow-circle-right
    url: 'https://getgrav.org'
    target: _blank
sidebar: true
menu_langswitcher: true
menu_search: true
menu_login: true
enable_social: true
custommenus:
  enabled: true
recent_posts_enabled: true
recent_posts_number: 7
social_style: brands